spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI5t6Hsous9HoD7F7PNLgk
      secret-key: lHm1uCxESIBjsJVwQYW8oX3VoCwcLe
      oss:
        endpoint: oss-cn-guangzhou.aliyuncs.com
        bucket: nutf4n
  application:
    name: guli-third-party

server:
  port: 30000



